---
- when: setup_postgres == True
  import_tasks: postgres-facts.yml


- import_tasks: project.yml


- when: build_frontend == True
  import_tasks: frontend.yml


- import_tasks: release.yml


- name: start nginx using monit
  monit: name="nginx" state=started
