---
- import_tasks: common.yml

- name: "check for swap file path"
  stat: path="/swap"
  register: swap_info


- when: create_swap_file == True and swap_info.stat.exists == False
  import_tasks: create-swap-file.yml


- import_tasks: pip.yml
- import_tasks: deployer-user.yml
- import_tasks: asdf.yml


- when: setup_postgres == True
  import_tasks: postgres-facts.yml
  tags:
    - debug

- when: setup_postgres == True
  import_tasks: postgres.yml


- import_tasks: project.yml


- when: build_frontend == True
  import_tasks: frontend.yml


- import_tasks: nginx.yml
- import_tasks: monit.yml
- import_tasks: release.yml
- import_tasks: databases.yml


- name: start nginx using monit
  monit: name="nginx" state=started


- name: reload nginx config
  service: name=nginx state=reloaded
