---
- when: action == "remove-app"
  import_tasks: action-remove-app.yml

- when: action == "setup"
  import_tasks: action-setup.yml

- when: action == "deploy"
  import_tasks: action-deploy.yml

- when: action == "migrate"
  import_tasks: action-migrate.yml

- when: action == "run-cmd"
  import_tasks: action-run-cmd.yml
